import Header from '@/components/Header'
import './globals.css'
import PageTransition from '@/components/PageTransition'
import StairTransition from '@/components/StairTransition'

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <PageTransition>
        <Header />
        <StairTransition />
        {children}
        </PageTransition>
      </body>
    </html>
  )
}
